### ISSUE TITLE
fontawesome usage

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/wp-menu-cart#2]
The cart icon is pulled from FontAwesome, but loading the complete font for every page when just using that one glyph is overkill. We could create a new font (with new name) that only contains this glyph and use that instead. SVG could be an alternative option but may not be nice for backwards compatibility.

**Comment by Spreeuw** [comment]
@alexmigf fantastic work! The environment will thank you 💯 

 - 87 000 sites
 - -95.7 KB +1.22 KB = -94.48 KB (WOFF)
 - 0,5 kWh per GB
 - ~10 000 unique visitors per month 

87 000 * (0.5 / 1 000 000) * 94.48 * 10 000 = **41 098.8** kWh / month energy savings!!!
That's the electricity usage of over **10 households**!

or... 41 098.8 * 0.295 = **12 124 kg of CO2** / month.

https://dannyvankooten.com/website-carbon-emissions/

**Comment by Spreeuw** [comment]
@alexmigf just noticed that the font size has changed for some reason, this needs to be fixed because the output should remain the same.
Before:
![menucart-font-awesome-size](https://user-images.githubusercontent.com/3217773/81380253-da83e980-910a-11ea-96a1-78d11d1560ab.png)

After:
![menucart-custom-font-size](https://user-images.githubusercontent.com/3217773/81380257-dd7eda00-910a-11ea-9939-31b8f04b8554.png)

also, small nitpick: if you fix an issue with a commit in a branch, the issue should remain open until the branch is merged.

**Comment by alexmigf** [comment]
@Spreeuw can you test?

**Comment by Spreeuw** [comment]
@alexmigf LGTM - I see a VERY minimal difference but wouldn't worry about that.
<img src="https://user-images.githubusercontent.com/3217773/81394656-91d82a80-9122-11ea-8feb-642d8ab0f086.png" width="1032px" />
<img src="https://user-images.githubusercontent.com/3217773/81394657-9270c100-9122-11ea-97c5-4eedaa1cf9d5.png" width="1032px" />
