### ISSUE TITLE
Compatibility with EDD Pro

### ISSUE THREAD

**Issue by dwalkerpriv** [wpovernight/wp-menu-cart#41]
Compatibility error with EDD Pro:
"WP Menu Cart could not detect an active shop plugin. Make sure you have activated at least one of the supported plugins"

**Comment by alexmigf** [comment]
EDD Pro is a new plugin: https://easydigitaldownloads.com/blog/edd-3-1-1-release-edd-pro/

**Comment by alexmigf** [comment]
@bshah-updraftplus we will need to contact EDD for give us a copy for testing, let's discuss that on Slack.

**Comment by bshah-updraftplus** [comment]
Yes that is something i have done on the above commit, added pro next to the plugin name and that allowed to go further without causing error.

PR : https://github.com/wpovernight/wp-menu-cart/pull/42
