### ISSUE TITLE
Test compatibility with EDD 3.0

### ISSUE THREAD

**Issue by Spreeuw** [wpovernight/wp-menu-cart#9]
Received via email:

> We are emailing you because WP Menu Cart needs to be tested against version 3.0 of Easy Digital Downloads.
> 
> We recently released the first beta version of 3.0 for developers to begin testing their integrations with. You can read about the beta version here: https://easydigitaldownloads.com/development/2021/02/16/edd-3-0-beta1/
> 
> There are a lot of changes in version 3.0, including new reporting APIs, new database tables, and numerous new functions and classes.
> 
> To help ensure that stores are able to update to version 3.0 as smoothly as possible, we're asking you to please test your extension and your websites with the 3.0 beta.
> 
> If you discover any problems, please open an issue on GitHub. If you have general feedback, please start a discussion. There are links below to help you:
> 
> - Github issues: https://github.com/easydigitaldownloads/easy-digital-downloads/issues
> - Github discussions: https://github.com/easydigitaldownloads/easy-digital-downloads/discussions
> - Beta 1 announcement post: https://easydigitaldownloads.com/development/2021/02/16/edd-3-0-beta1/
> 
> Once you have tested your extension and confirmed compatibility with version 3.0, will you please reply to this email and let us know so that we can keep track of the extensions that are confirmed to be 3.0 compatible?
> 
> We also welcome you to reply directly to this email with questions or comments.
> 
> Thank you for being part of the Easy Digital Downloads development community!
> 
> Pippin,
> Founder and Managing Director of Sandhills Development
> On behalf of the Easy Digital Downloads Team

**Comment by alexmigf** [comment]
Seems to be working fine, also Pro version, no errors or bugs in logs.
